I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 128, in script
    Nurse "Doctor. The patient's awake. Shall we run the diagnostics?"
Exception: Sayer 'Nurse' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 128, in script
    Nurse "Doctor. The patient's awake. Shall we run the diagnostics?"
  File "C:\Users\NewUsername\Desktop\renpy-6.99.12.4-sdk\renpy\ast.py", line 593, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\NewUsername\Desktop\renpy-6.99.12.4-sdk\renpy\ast.py", line 509, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'Nurse' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Adventure 1.0
